name: material_guardian_mobile
description: "Shared Material Guardian mobile client."
publish_to: 'none'
version: 1.0.5+6

environment:
  sdk: ^3.11.4

dependencies:
  archive: ^4.0.9
  camera: ^0.11.0+2
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  http: ^1.5.0
  image_picker: ^1.2.1
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0+10
  open_filex: ^4.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.12.0
  share_plus: ^12.0.2
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/reference/android-source/icons/
