name: material_guardian_mobile
description: "Shared Material Guardian mobile client."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  archive: ^4.0.9
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  image_picker: ^1.2.1
  open_filex: ^4.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.12.0
  share_plus: ^12.0.2
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
